import { test, expect, Page, BrowserContext } from '@playwright/test';

/**
 * Flipkart Washing Machine Search & Cart Test
 * File: demoflipkart10.spec.ts
 * Generated by Claude (Anthropic) via Playwright MCP
 * Date: 2026-03-23
 *
 * Test Steps:
 * 1. Navigate to flipkart.com
 * 2. Handle login popup if it appears
 * 3. Search for "washing machine"
 * 4. Press Enter to search
 * 5. Click first Sponsored/AD product (fallback to first product)
 * 6. Switch to new tab if product opens in new tab
 * 7. Extract product details (name, price, rating, availability)
 * 8. Click Add to Cart / Buy now
 * 9. Verify product in cart
 * 10. Verify product name contains "washing"
 * 11. Log all captured data
 */

interface ProductDetails {
  name: string;
  price: string;
  rating: string;
  availability: string;
  url: string;
}

interface CartVerification {
  cartPageLoaded: boolean;
  productInCart: boolean;
  nameContainsWashing: boolean;
  cartItemName: string;
  cartItemPrice: string;
  priceMatchesSelected: boolean;
}

test.describe('Flipkart Washing Machine - Search, Select & Cart Verification', () => {
  let productDetails: ProductDetails;
  let cartVerification: CartVerification;

  test('TC01 - Search Washing Machine, Select Sponsored Product & Add to Cart', async ({ browser }) => {
    const context: BrowserContext = await browser.newContext({
      viewport: { width: 1280, height: 800 },
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36'
    });
    const page: Page = await context.newPage();

    // ── STEP 1: Navigate to Flipkart ──────────────────────────────────────────
    console.log('\n[STEP 1] Navigating to https://www.flipkart.com ...');
    await page.goto('https://www.flipkart.com', { waitUntil: 'domcontentloaded', timeout: 30000 });
    await expect(page).toHaveTitle(/Flipkart/i);
    console.log('[STEP 1] ✅ Flipkart homepage loaded');

    // ── STEP 2: Handle login popup ────────────────────────────────────────────
    console.log('\n[STEP 2] Checking for login popup...');
    try {
      const closeBtn = page.locator('button._2KpZ6l._2doB4z, [class*="modal"] button[class*="close"]').first();
      if (await closeBtn.isVisible({ timeout: 3000 })) {
        await closeBtn.click();
        console.log('[STEP 2] ✅ Login popup closed');
      } else {
        console.log('[STEP 2] ✅ No login popup found');
      }
    } catch {
      console.log('[STEP 2] ✅ No login popup found');
    }

    // ── STEP 3 & 4: Search for "washing machine" ──────────────────────────────
    console.log('\n[STEP 3] Searching for "washing machine"...');
    const searchInput = page.locator('input[title="Search for Products, Brands and More"]');
    await searchInput.click();
    await searchInput.fill('washing machine');
    await page.keyboard.press('Enter');

    // ── STEP 5: Wait for search results ──────────────────────────────────────
    console.log('\n[STEP 5] Waiting for search results...');
    await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
    await page.waitForTimeout(3000);
    await expect(page).toHaveURL(/search\?q=washing/i);
    console.log('[STEP 5] ✅ Search results loaded');
    console.log(`         URL: ${page.url()}`);

    // ── STEP 6: Find first Sponsored/AD product ───────────────────────────────
    console.log('\n[STEP 6] Locating first Sponsored product...');
    const targetProductLink = await page.evaluate(() => {
      const cards = document.querySelectorAll('div[data-id]');
      // First try: find a product with "Sponsored" label
      for (const card of cards) {
        const text = card.innerText || '';
        const link = card.querySelector('a[href*="/p/"]') as HTMLAnchorElement;
        const href = link?.href || '';
        if (text.includes('Sponsored') || href.includes('fm=ad') || href.includes('fm=p2pad')) {
          return { href, isSponsored: true, name: text.substring(0, 80) };
        }
      }
      // Fallback: use first product card
      const firstCard = cards[0];
      const firstLink = firstCard?.querySelector('a[href*="/p/"]') as HTMLAnchorElement;
      const firstText = firstCard?.innerText || '';
      return { href: firstLink?.href || '', isSponsored: false, name: firstText.substring(0, 80) };
    });

    console.log(`[STEP 6] ${targetProductLink.isSponsored ? '✅ Sponsored product found' : '⚠️  No sponsored product - using first result'}`);
    console.log(`         Product: ${targetProductLink.name.trim().split('\n')[0]}`);
    expect(targetProductLink.href).toBeTruthy();

    // ── STEP 7: Click the product (handle new tab) ────────────────────────────
    console.log('\n[STEP 7] Clicking product - watching for new tab...');
    const [newPage] = await Promise.all([
      context.waitForEvent('page', { timeout: 10000 }).catch(() => null),
      page.locator('div[data-id] a[href*="/p/"]').first().click()
    ]);

    let productPage: Page;
    if (newPage) {
      productPage = newPage;
      console.log('[STEP 7] ✅ Product opened in new tab - switched to new tab');
    } else {
      productPage = page;
      console.log('[STEP 7] ✅ Product opened in same tab');
    }

    await productPage.waitForLoadState('domcontentloaded', { timeout: 20000 });
    await productPage.waitForTimeout(3000);

    // ── STEP 8: Extract product details ──────────────────────────────────────
    console.log('\n[STEP 8] Extracting product details...');
    await productPage.evaluate(() => window.scrollTo(0, 300));
    await productPage.waitForTimeout(1000);

    const extractedDetails = await productPage.evaluate(() => {
      const pageTitle = document.title || '';
      const name = pageTitle.split(' Price in India')[0].trim();
      const priceEl = document.querySelector('div._30jeq3');
      const price = priceEl ? (priceEl as HTMLElement).innerText.trim() : '';
      const ratingEl = document.querySelector('div._3LWZlK');
      const rating = ratingEl ? (ratingEl as HTMLElement).innerText.trim() : 'N/A';
      const bodyText = document.body.innerText || '';
      const isOutOfStock = bodyText.toLowerCase().includes('out of stock');
      const availability = isOutOfStock ? 'Out of Stock' : 'In Stock';
      return { name, price, rating, availability, url: window.location.href };
    });

    productDetails = extractedDetails;

    console.log('\n  ╔═══════════════════════════════════════════════╗');
    console.log('  ║         CAPTURED PRODUCT DETAILS              ║');
    console.log('  ╠═══════════════════════════════════════════════╣');
    console.log(`  ║ Name        : ${productDetails.name.substring(0, 38)}...`);
    console.log(`  ║ Price       : ${productDetails.price}`);
    console.log(`  ║ Rating      : ${productDetails.rating} ★`);
    console.log(`  ║ Availability: ${productDetails.availability}`);
    console.log('  ╚═══════════════════════════════════════════════╝\n');

    expect(productDetails.name).toBeTruthy();
    expect(productDetails.price).toMatch(/₹[\d,]+/);

    // ── STEP 9: Add to Cart / Buy Now ─────────────────────────────────────────
    console.log('\n[STEP 9] Clicking Add to Cart / Buy Now...');
    const addToCartClicked = await productPage.evaluate(() => {
      const allElements = document.querySelectorAll('*');
      for (const el of allElements) {
        const text = (el.childNodes.length <= 3 ? el.textContent || '' : '').trim();
        if (['Add to Cart', 'ADD TO CART', 'Buy now', 'BUY NOW'].includes(text)) {
          (el as HTMLElement).click();
          return { success: true, buttonText: text };
        }
      }
      return { success: false, buttonText: '' };
    });

    if (addToCartClicked.success) {
      console.log(`[STEP 9] ✅ Clicked "${addToCartClicked.buttonText}" button`);
    } else {
      console.log('[STEP 9] ⚠️  Add to Cart button not found - navigating to cart directly');
    }
    await productPage.waitForTimeout(3000);

    // ── STEP 10: Navigate to cart ─────────────────────────────────────────────
    console.log('\n[STEP 10] Navigating to cart page...');
    await productPage.goto('https://www.flipkart.com/viewcart?marketplace=FLIPKART', {
      waitUntil: 'domcontentloaded', timeout: 20000
    });
    await productPage.waitForTimeout(3000);
    console.log('[STEP 10] ✅ Cart page loaded');

    // ── STEP 11: Verify cart contents ─────────────────────────────────────────
    console.log('\n[STEP 11] Verifying cart contents...');
    const cartData = await productPage.evaluate((selectedPrice: string) => {
      const bodyText = document.body.innerText || '';
      const pageTitle = document.title;

      // Find cart item that contains "washing machine"
      const washingMachineRegex = /[A-Za-z0-9 ]+[Ww]ashing [Mm]achine[^\n]*/g;
      const matches = bodyText.match(washingMachineRegex) || [];
      const cartItemName = matches.length > 0 ? matches[0].trim() : '';

      // Find price in cart
      const priceMatches = bodyText.match(/₹[\d,]+/g) || [];
      const cartItemPrice = priceMatches.length > 0 ? priceMatches[0] : '';

      return {
        cartPageLoaded: pageTitle.toLowerCase().includes('cart'),
        productInCart: bodyText.toLowerCase().includes('washing machine'),
        nameContainsWashing: cartItemName.toLowerCase().includes('washing'),
        cartItemName: cartItemName.substring(0, 100),
        cartItemPrice,
        priceMatchesSelected: cartItemPrice === selectedPrice || priceMatches.some(p => p === selectedPrice)
      };
    }, productDetails.price);

    cartVerification = cartData;

    // ── STEP 12: Log all captured data ───────────────────────────────────────
    console.log('\n');
    console.log('╔══════════════════════════════════════════════════════════════╗');
    console.log('║           FLIPKART TEST - FINAL VERIFICATION REPORT         ║');
    console.log('╠══════════════════════════════════════════════════════════════╣');
    console.log('║  SELECTED PRODUCT DETAILS                                   ║');
    console.log(`║  Name        : ${productDetails.name.substring(0, 46)}`);
    console.log(`║  Price       : ${productDetails.price}`);
    console.log(`║  Rating      : ${productDetails.rating} ★`);
    console.log(`║  Availability: ${productDetails.availability}`);
    console.log('╠══════════════════════════════════════════════════════════════╣');
    console.log('║  CART VERIFICATION RESULTS                                  ║');
    console.log(`║  Cart Page Loaded         : ${cartVerification.cartPageLoaded ? '✅ PASS' : '❌ FAIL'}`);
    console.log(`║  Washing Machine In Cart  : ${cartVerification.productInCart ? '✅ PASS' : '❌ FAIL'}`);
    console.log(`║  Name Contains "washing"  : ${cartVerification.nameContainsWashing ? '✅ PASS' : '❌ FAIL'}`);
    console.log(`║  Cart Item Name           : ${cartVerification.cartItemName.substring(0, 46)}`);
    console.log(`║  Cart Item Price          : ${cartVerification.cartItemPrice}`);
    console.log('╚══════════════════════════════════════════════════════════════╝');

    // ── ASSERTIONS ────────────────────────────────────────────────────────────
    // Assertion 1: Cart page loaded successfully
    expect(cartVerification.cartPageLoaded,
      'Cart page should load with title containing "Cart"').toBeTruthy();

    // Assertion 2: Washing machine product is present in cart
    expect(cartVerification.productInCart,
      'Cart should contain a washing machine product').toBeTruthy();

    // Assertion 3: Product name contains "washing" keyword
    expect(cartVerification.nameContainsWashing,
      'Cart product name should contain "washing" keyword').toBeTruthy();

    // Assertion 4: Cart item name is not empty
    expect(cartVerification.cartItemName.length,
      'Cart item name should not be empty').toBeGreaterThan(0);

    // Assertion 5: Product name from search contains "washing"
    const productNameLower = productDetails.name.toLowerCase();
    expect(productNameLower,
      'Selected product name should contain "washing"').toContain('washing');

    console.log('\n[TEST RESULT] ✅ ALL ASSERTIONS PASSED SUCCESSFULLY');
    await context.close();
  });
});
